name = "QSGRegistry"
repo = "git@github.com:ggggggggg/QSGRegistry.jl.git"
uuid = "eb067caa-c9e6-11e9-251d-818cfd6be9f4"

[packages]
a30f7cd4-c816-11e9-3b7b-4b2248985146 = { name = "Pope", path = "P/Pope" }
cce409be-c91d-11e9-3263-d35f6180a8ba = { name = "ReferenceMicrocalFiles", path = "R/ReferenceMicrocalFiles" }
cd9ce936-d6d7-11e8-0157-ada3f5245b07 = { name = "ARMA", path = "A/ARMA" }
